
export interface UsersRegistrationRequest {
    'id' : Number,
    'department_name': string,
    'room_number': string,
    'name': string,
    'designation': string,
    'phone': string,
    'email': string,
    'website': string,
    'photo': string,
    'biographyFiledOfSpecialization': string,
    'researchInterest': string,
    'currentResearchAndCollaboration': string,
    'fellowshipOfScientificAndProfessionalSociaties': string,
    'educationExperience': string,
    'teachingExperience': string,
    'researchExperience': string,
    'awardAndRecognition': string,
    'publication': string,
    'journals': string,
    'conference': string,
    'graduateSupervision': string,
    'courseOffered': string,
    'roles': string,
}
